name: Deploy Flutter Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Flutter Web App
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Get dependencies
        run: flutter pub get
      
      - name: Build web App
        # run: flutter build web
        run: flutter build web --base-href "/ProposalPro/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true
          user_name: 'github-ci[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Publish to gh-pages'