name: Deploy Flutter Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Flutter Web App
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build web App
        run: flutter build web
      
      - name: Changing Working Dir
        run: mkdir Payload
        working-directory: build/web
        
      - name: Set Git user identity
        run: |
          git config --global user.email "sabin.ghimire1827@gmail.com"
          git config --global user.name "Saw2110"
  
      - name: Clean release branch
        run: |
          if git show-ref --verify --quiet refs/heads/release; then
            git checkout release
            git rm -r .
            git commit -m "Deleted all files from branch"
          else
            git checkout -b release
            git push origin release
          fi
        
      - name: Copy build files to release branch
        working-directory: build/web/
        run: |
          git add .
          git commit -m "Update release branch with new build"
          git pull origin release
          git push origin release
